name: CI

on:
  push: # all branches

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    name: Test & Deploy
    steps:
      - name: Download codebase
        uses: actions/checkout@v2

      - name: Set up Node.js v14
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: npm
      
      - name: Install dependencies
        run: npm ci

      - name: Run tests & measure coverage
        run: npm test -- --coverage

      - name: Update Codecov
        uses: codecov/codecov-action@v1

      - name: Build & lint
        run: npm run build

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          npm run deploy
        env:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          github_token: ${{ secrets.GH_PAGES_DEPLOY_KEY }}
          repository: ${{ github.repository }}
